#!/bin/sh
#此脚本解决vmware workstation克隆centos时eth0配置中MAC保留原镜像MAC
#导致网络服务不可用
#包括mac修改、ip、子网掩码、网关、dns设置
#在虚拟机做成镜像前，执行下面语句
# rm -f /etc/udev/rules.d/70-persistent-net.rules
# sed -i '/HWADDR.*\|UUID.*/d' /etc/sysconfig/network-scripts/ifcfg-eth0
# echo "sh /root/ip.sh" >> /etc/bashrc
#在root目录下，复制本脚本内容到ip.sh

#检查ip合规性
checkip ()
{
	ip=$1
	if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];then
		ip=(${ip//./ })
		for i in ${ip[@]}
		do
			[[ $i -le 255 ]] || exit 2
		done 
	else
		exit 3
	fi
}

read -p "input ip address:" IP_ADDR
checkip $IP_ADDR
sed -i "s/\(IPADDR=\).*/\1${IP_ADDR}/" /etc/sysconfig/network-scripts/ifcfg-eth0

read -p "input netmask:" NET_MASK
checkip $NET_MASK
sed -i "s/\(NETMASK=\).*/\1${NET_MASK}/" /etc/sysconfig/network-scripts/ifcfg-eth0

read -p "input GATEWAY:" GATE_WAY
checkip $GATE_WAY
sed -i "s/\(GATE_WAY=\).*/\1${GATE_WAY}/" /etc/sysconfig/network-scripts/ifcfg-eth0

read -p "input DNS:" DNS
checkip $DNS
echo "nameserver $DNS" > /etc/resolv.conf

#生成新设备MAC
awk -F '"' '$14=="eth0"{print "HWADDR="$8}' /etc/udev/rules.d/70-persistent-net.rules >> /etc/sysconfig/network-scripts/ifcfg-eth0
#删除脚本相关文件
sed -i '$'d /etc/bashrc
rm -f $0

/etc/init.d/network restart
